# -- generic settings ---------------------------------------------------------

# fixes problem with copy & paste on macOS
# 2023-05-04: not needed anymore
# 2024-11-08: as of v3.5a, it is needed again (default is back to default-command "reattach-to-user-namespace -l /bin/sh")
set -g default-command 'reattach-to-user-namespace -l /opt/homebrew/bin/zsh'

# -- plugin management --------------------------------------------------------

# set -ga @plugin 'tmux-plugins/example-of-os-specific-plugin'
